name = "new-bybit"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "new-bybit"
workers_dev = true

[vars]
ENVIRONMENT = "production"
